# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: default
spec:
  selector:
    app: test
  type: ClusterIP
  ports:
  - name: test
    protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30001
